- .pre-commit-config.yaml
- mmaction/core/optimizer/copy_of_sgd.py
- mmaction/datasets/pipelines/augmentations.py
- mmaction/datasets/pipelines/loading.py
- mmaction/datasets/samplers/distributed_sampler.py
- mmaction/models/backbones/resnet2plus1d.py
- mmaction/models/losses/binary_logistic_regression_loss.py
- mmaction/models/recognizers/base.py
- mmaction/models/recognizers/recognizer2d.py
- mmaction/models/recognizers/recognizer3d.py
- requirements/optional.txt
- requirements/tests.txt
- tests/test_models/test_recognizers.py
- tools/data/kinetics400/download.py
- Add [docformatter](https://github.com/myint/docformatter) in pre-commit
- Update docstring formats
- Update version of some pre-commit hooks
> Update docstring formats using docformatter

- docs/getting_started.md
- docs/tutorials/new_dataset.md
- tools/test.py
* Remove redundant `how-to` part, since it is similar to the content in tutorials.
* Remove unused args `gpus` in `tools/test.py` and update the docs.
> Polish docs

- configs/recognition/tsm/tsm_temporal_pool_r50_1x1x8_50e_kinetics400_rgb.py
- mmaction/models/backbones/resnet_tsm.py
- tests/test_models/test_backbone.py
Fix [this issue](https://github.com/open-mmlab/mmaction2/issues/38). 
Since [original repo](https://github.com/mit-han-lab/temporal-shift-module) doesn't use this function but still provides this function in the codes, we supplement it to make temporal pooling between layer1 and layer2, using a 3D max pooling layer and provide the example config file.
> Support temporal pool in tsm

- docs/data_preparation.md
- tools/data/build_file_list.py
- tools/data/build_rawframes.py
- tools/data/mit/download_data.sh
- tools/data/parse_file_list.py
- tools/data/thumos14/download_annotations.sh
- tools/data/thumos14/download_videos.sh
- tools/data/ucf101/download_annotations.sh
- tools/data/ucf101/download_videos.sh
- tools/data/ucf101/extract_frames.sh
- tools/data/ucf101/preparing_ucf101.md
* use a more elegant way to manipulate directory and files in python scripts.
* update ucf101 url with the latest one.
* minor fix in data bash scripts (ensure the directory exist before `cd`).
> Data preparation update

- mmaction/models/heads/tsm_head.py
support multi class in TSM head
> support multi class in tsm head

- mmaction/models/backbones/resnet_tsm.py
https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/bricks/non_local.py#L178
> Avoid contiguous error when implementing guassian nonlocal

- configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_rgb.py
- configs/recognition/slowonly/slowonly_r50_8x8x1_256e_kinetics400_rgb.py
Fix the learning rate of slowonly to 8gpus default value.
> Fix lr to 8gpus in slowonly

- mmaction/models/heads/i3d_head.py
- mmaction/models/heads/slowfast_head.py
- mmaction/models/heads/tsm_head.py
- mmaction/models/heads/tsn_head.py
Move multi-class and stuff to **kwargs, do not need to add it once a new head appears.
> Fix the multi-class support in a cleaner way.

- docs/data_preparation.md
- tools/flow_extraction.py
@dreamerlin  This PR to generalize `tools/flow_extraction.py` for flow extraction of one or several videos, docs also added.
> Flow extraction doc

- docs/tutorials/new_dataset.md
Just fix typo in docs/tutorials/new_dataset.md.
BaseDatset -> BaseDataset
Best.
> Fix typo in docs/tutorials/new_dataset.md

- configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py
- demo/webcam_demo.py
- docs/changelog.md
- docs/getting_started.md
This PR adds webcam demo for real-time recognition to solve https://github.com/open-mmlab/mmaction2/issues/153
> Add webcam demo code

- mmaction/models/backbones/resnet3d_slowfast.py
Slice and interpolate are equivalent.
> Use interpolate instead of slice to support onnx.

- configs/localization/bmn/README.md
- docs/changelog.md
- mmaction/core/evaluation/__init__.py
- mmaction/core/evaluation/eval_detection.py
- tools/analysis/report_map.py
Last PR mess up after rebase, so I reopen a new one.
> Report mAP with cuhk_anet17_pred

- configs/recognition/i3d/i3d_r50_video_inference_32x2x1_100e_kinetics400_rgb.py
- configs/recognition/r2plus1d/r2plus1d_r34_video_inference_8x8x1_180e_kinetics400_rgb.py
- configs/recognition/slowfast/slowfast_r50_video_inference_4x16x1_256e_kinetics400_rgb.py
- configs/recognition/slowonly/slowonly_r50_video_inference_4x16x1_256e_kinetics400_rgb.py
- configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py
- demo/webcam_demo.py
- docs/getting_started.md
This PR makes `webcam_demo.py` not only supports `TSN`, but also other recognizers which need enough frames for inference at the beginning to do real-time recognition. Also, this PR updates the docs for how to make efficient real-time action recognition.
> [Enhance] Async inference of webcam demo

- configs/recognition/tsn/tsn_r50_320p_1x1x8_150e_activitynet_video_flow.py
- configs/recognition/tsn/tsn_r50_320p_1x1x8_50e_activitynet_video_rgb.py
- docs/getting_started.md
- docs/tutorials/finetune.md
- mmaction/datasets/activitynet_dataset.py
- mmaction/models/localizers/bmn.py
- mmaction/models/localizers/bsn.py
- mmaction/models/localizers/utils/post_processing.py
- tests/test_models/test_localizers.py
- tools/data/activitynet/generate_rawframes_filelist.py
- tools/data/activitynet/preparing_activitynet.md
- tools/data/activitynet/tsn_feature_extraction.py
- tools/test.py
- tools/train.py
1. support custom feature extraction interval like in [`tsn_feature_extraction.py`](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/tsn_feature_extraction.py#L22-L26), useful for other (e.g. custom) dataset
2. fix typo in docs
3. anno file name in tsn anet config should be consistence with [generated filename](https://github.com/open-mmlab/mmaction2/blob/master/tools/data/activitynet/generate_rawframes_filelist.py#L70-L73)
> some anet related improvements

- docker/Dockerfile
- docs/changelog.md
- docs/install.md
- requirements/runtime.txt
This PR updates docker file to support PyTorch 1.6 and `install.md`.
> [Enhance] Update docker file and install.md

- mmaction/version.py
It can be merged after https://github.com/open-mmlab/mmaction2/pull/230
> bump version to 0.7.0

- README.md
- docs/data_preparation.md
- docs/merge_docs.sh
- docs/supported_datasets.md
Links in [supported_datasets.md](https://github.com/open-mmlab/mmaction2/blob/master/docs/supported_datasets.md) are invalid.
> [Improvement] Polish supported_datasets.md

- README.md
Fix https://github.com/open-mmlab/mmaction2/issues/246
> [Fix] Fix modelzoo link for README

- mmaction/version.py
After https://github.com/open-mmlab/mmaction2/pull/298
> bump version to 0.8.0

- docs/changelog.md
- docs/conf.py
- docs/index.rst
- docs/install.md
- docs/stat.py
- mmaction/__init__.py
This PR will add modelzoo statistics including number of config files, checkpoints etc. to readthedocs pages, which is mostly referred from https://github.com/open-mmlab/mmpose/pull/252
> [Feature] Auto modelzoo statistics

- tools/test.py
This PR follows https://github.com/open-mmlab/mmaction2/pull/346 : )
> fix test bug

- docs/merge_docs.sh
> [Docs] Update readthedocs with audio recognition models

- configs/recognition/tsn/README.md
Adding a new blank line above markdown table, to solve the problem that this markdown table can not be renderred correctly.
> Reformat TSN config README.md

- mmaction/datasets/audio_visual_dataset.py
- mmaction/models/backbones/resnet_audio.py
Use the new version of module registration so that no deprecation warnings arise.
> Fix deprecated registration

- .github/workflows/build.yml
- docs/changelog.md
> [Improvement] modify CI config

- configs/recognition/c3d/README.md
- docs/stat.py
This PR formats the style of paper name for C3D and regex used for collecting papers.
Refs: https://github.com/open-mmlab/mmpose/pull/345/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721
> [Docs] fix paper_retrieval bug

- docs/install.md
update installation doc
Fixes #479
> update installation doc

- configs/detection/ava/README.md
- configs/localization/bmn/README.md
- configs/recognition/c3d/README.md
- configs/recognition/csn/README.md
- configs/recognition/i3d/README.md
- configs/recognition/tsm/README.md
Add double quotes to the title of the papers that don't propose models so that they will be ignored in modelzoo statistics
> modify papers title in README.md

- tools/data/ucf101/README.md
> Fix typos in README.md

- docs/merge_docs.sh
- docs/stat.py
Signed-off-by: lizz <lizz@sensetime.com>
> Add paper links

- docs/stat.py
Signed-off-by: lizz <lizz@sensetime.com>
> Replace more strange chars

- docs/changelog.md
Signed-off-by: lizz <lizz@sensetime.com>
> Refactor is improvement

- README.md
- mmaction/version.py
> Bump version to v0.11.0

- docs/faq.md
This PR updates FAQ for:
- https://github.com/open-mmlab/mmaction2/issues/525
- https://github.com/open-mmlab/mmaction2/issues/441
> [docs] Update FAQ

- tools/data/activitynet/README.md
- tools/data/activitynet/download.py
- tools/data/activitynet/download_annotations.sh
- tools/data/activitynet/download_bsn_videos.sh
- tools/data/activitynet/download_feature_annotations.sh
- tools/data/activitynet/generate_rawframes_filelist.py
This PR updates ActivityNet video download steps since the original one is used the annotation from BSN repo rather than the official one. The number of items in BSN annotation is less than that in official.
> Fix anet video downloader

- tools/test.py
> Fix config refactor bug

- README.md
- docs/README_cn.md
- docs/changelog.md
1. Add changelog
2. update EN README
3. update CN README and fix some links in it
> prepare for release

- configs/recognition/tsm/tsm_r50_gpu_normalize_1x1x8_50e_kinetics400_rgb.py
- mmaction/utils/module_hooks.py
- setup.cfg
- tests/test_utils/test_module_hooks.py
- tools/test.py
- tools/train.py
bmn, bsn have no backbone to register module hook.
fix #666
> fix module hook bug

- configs/recognition/tsn/tsn_r50_320p_1x1x3_110e_kinetics400_flow.py
- configs/recognition/tsn/tsn_r50_320p_1x1x8_110e_kinetics400_flow.py
> [Fix] fix flow norm cfg typo

- README.md
- README_zh-CN.md
https://github.com/open-mmlab/mmaction2/tree/d24767b1a9baf05ef878a504317226db371faef0/docs_zh_CN
https://github.com/open-mmlab/mmaction2/tree/d24767b1a9baf05ef878a504317226db371faef0
https://github.com/open-mmlab/mmaction2/blob/d24767b1a9baf05ef878a504317226db371faef0/README_zh-CN.md
> update image url

- tests/test_models/test_common_modules/test_base_recognizers.py
> Add unit test for `average_clips=None`

- docs_zh_CN/install.md
> [Docs] Fix typo in CN install.md

- tools/data/kinetics/README.md
- tools/data/kinetics/README_zh-CN.md
Host by Common Visual Data Foundation. I'm downloading now.
可以用迅雷下载！！！！
> [Improvement] Alternative way to download kinetics

- docs/changelog.md
> add changelog for v0.15.0

- demo/faster_rcnn_r50_fpn_2x_coco.py
> update nms config in demo/faster_rcnn

- mmaction/models/backbones/resnet3d.py
Update missing docstrings
Updated docstrigns
> Update ResNet3d docstring with missing args

- configs/detection/acrn/metafile.yml
- configs/recognition/c3d/metafile.yml
- configs/recognition/csn/metafile.yml
- configs/recognition/i3d/metafile.yml
- configs/recognition/omnisource/metafile.yml
- configs/recognition/r2plus1d/metafile.yml
- configs/recognition/slowfast/metafile.yml
- configs/recognition/slowonly/metafile.yml
- configs/recognition/tanet/metafile.yml
- configs/recognition/tin/metafile.yml
- configs/recognition/tpn/metafile.yml
- configs/recognition/trn/metafile.yml
- configs/recognition/tsm/metafile.yml
- configs/recognition/tsn/metafile.yml
- configs/recognition/x3d/metafile.yml
- configs/recognition_audio/resnet/metafile.yml
- configs/skeleton/posec3d/metafile.yml
Update Metafiles according to MIM requirements.
> [Fix] Update metafiles

- .pre-commit-config.yaml
- mmaction/datasets/builder.py
> [Feature] add persistent worker 

- mmaction/datasets/__init__.py
- mmaction/datasets/builder.py
- mmaction/datasets/dataset_wrappers.py
- tests/test_data/test_datasets/test_concat_dataset.py
- tests/test_data/test_datasets/test_repeat_dataset.py
1. Support ConcatDataset
2. Refactor build_dataset
> [Feature] Support ConcatDataset

- docs/feature_extraction.md
- docs_zh_CN/feature_extraction.md
This PR contains the following items:
1. Add Chinese translation of feature_extraction.md.
2. Fix typo in the subtitle of the English feature_extraction.md.
> [Docs] Add Chinese translation of feature_extraction.md

- mmaction/models/recognizers/recognizer3d.py
Currently, `Timesformer` is not compatible with the feature extraction module in `recognizer3D`.
The current feature extraction module in `recognizer3D` is illustrated below:
```python
if self.feature_extraction:
avg_pool = nn.AdaptiveAvgPool3d(1)
if isinstance(feat, tuple):
feat = [avg_pool(x) for x in feat]
feat = torch.cat(feat, axis=1)
else:
feat = avg_pool(feat)
feat = feat.reshape((batches, num_segs, -1))
feat = feat.mean(axis=1)
return feat
```
This module is only compatible with `feat` of shape `(N, in_channels, T, H, W)`. However,`feat` in Timesformer are of shape `(N, in_channels)`, which requires no Pooling.
Add different branches according to `feat` shape.
> [fix] Support Timesformer feature extraction

- docs/tutorials/2_finetune.md
> Fixed Grammer

- .readthedocs.yml
- tools/data/activitynet/download.py
- tools/deployment/publish_model.py
1. Support Publish Model in Windows
2. Fix doc buliding
> [Feature] Support Publish Model in Windows

- docs/install.md
- docs_zh_CN/install.md
Fixes #1334. I think directly install from .git would be better.
> Update installation command

- tools/data/skeleton/ntu_pose_extraction.py
Fix missing skip_postproc parameter
add skip_postproc argc parameter
> Fix missing skip_postproc parameter

- mmaction/models/backbones/c3d.py
- tests/test_models/test_backbones.py
- tests/test_models/test_recognizers/test_recognizer3d.py
- tests/test_runtime/test_train.py
Refine CI, reduce the memory usage.
> [Improvement] Refine CI

- mmaction/apis/train.py
Copy from mmdetection 
https://github.com/open-mmlab/mmdetection/blob/98949809b7179fab9391663ee5a4ab5978425f90/mmdet/apis/train.py#L169
> [Feature] Support custom_hooks in mmaction/apis/train.py

- configs/skeleton/stgcn/README.md
I think the link for STGCN was wrong I guess ?
> update the link for the article

- mmaction/models/heads/stgcn_head.py
`kwargs` were missing from head
> [Improvement] Add kwargs to STGCNHead

- README.md
- README_zh-CN.md
> [Docs] fix install typo

- configs/recognition/slowfast/slowfast_multigrid_r50_8x8x1_358e_kinetics400_rgb.py
> [Update] Add lateral norm in multigrid config

- tools/data/ucf101/README.md
> Did not mention the addition of optical flow calculations

- docs/getting_started.md
- docs_zh_CN/demo.md
- docs_zh_CN/getting_started.md
1. Remove the wong argument same as PR #1580 in docs_zh_CN/getting_started.md.
2. Fix the wrong command line argument ` --font-size` in [docs_zh_CN ](https://mmaction2.readthedocs.io/zh_CN/latest/demo.html#id2).
> [Docs] Fix docs_zh_CN/demo.md & docs_zh_CN/getting_started.md

- mmaction/datasets/pipelines/formatting.py
- mmaction/datasets/pipelines/pose_loading.py
- mmaction/models/skeleton_gcn/utils/graph.py
- tests/test_data/test_pipelines/test_loadings/test_pose_loading.py
- tests/test_models/test_backbones.py
Open Pose also has 25 joints version. They are used by many popular pose estimation algorithms.
> [Improvement] Add openpose 25 joints to graph

- mmaction/datasets/pipelines/loading.py
> Fixed typo error at comment.

- demo/demo_video_structuralize.py
- demo/hrnet_w32_coco_256x192.py
Modify hrnet config to be in sync with https://github.com/open-mmlab/mmpose/pull/1311
> Fix hrnet config to handle mmpose/pull/1311

- mmaction/__init__.py
- mmaction/version.py
> [Refactor] Update Version 

- configs/recognition/i3d/metafile.yml
> [Fix] lint in i3d metafile.yml

- mmaction/datasets/video_dataset.py
> [refactor] update video dataset

- mmaction/datasets/video_dataset.py
- mmaction/models/backbones/tanet.py
> [refactor] refactor tanet

- requirements/docs.txt
> [Fix] fix doc dependency

- mmaction/datasets/rawframe_dataset.py
- mmaction/models/recognizers/recognizer3d.py
- mmaction/models/recognizers/recognizer_gcn.py
Fix some small bugs in recognizer_3d.py and refactor recognizer_gcn.py & rawframe_dataset.py
1. Pre-commit or other linting tools should be …
> [Refactor] Refactor recognizer

- tools/train.py
Refactor ``train.py`` to support ``--auto-scale-lr`` and ``--resume``
> [Refactor] support ``--auto-scale-lr`` and ``--resume``

- tools/model_converters/publish_model.py
Refactor ``publish_model.py`` to better process the publishing checkpoints.
> [Refactor] refactor publish model

- configs/recognition/c3d/README.md
- configs/recognition/c3d/metafile.yml
Update c3d Readme and metafile.
> [Refactor] Update C3D training configs

- configs/_base_/models/trn_r50.py
- configs/recognition/trn/README.md
- configs/recognition/trn/metafile.yml
- configs/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv1_rgb.py
- configs/recognition/trn/trn_r50_1x1x8_50e_8xb16_sthv2_rgb.py
> [Refactor] update trn

- configs/detection/acrn/README.md
- configs/detection/acrn/metafile.yml
- configs/detection/acrn/slowfast_acrn_kinetics400_pretrained_r50_8x8x1_cosine_10e_8xb8_ava22_rgb.py
- configs/detection/acrn/slowfast_acrn_kinetics400_pretrained_r50_8x8x1_cosine_10e_8xb8_ava_rgb.py
> [Refactor] Update ACRN training configs and README

- mmaction/__init__.py
- requirements/mminstall.txt
Update version requirements of mmcv and mmengine.
2. The …
> [Refactor] update mmcv version

- tools/analysis_tools/browse_dataset.py
> [Refactor] support browse_dataset

- mmaction/visualization/action_visualizer.py
> [Fix] fix visualizer bc-breaking from mmengine

- mmaction/version.py
update version from ``1.0.0rc`` to ``1.0.0rc0``.
> [Refactor] update version to 1.0.0rc0

- demo/demo.py
- docs/en/get_started.md
- mmaction/apis/inference.py
- mmaction/datasets/transforms/loading.py
> [Refactor] add get_started.md

- configs/localization/bmn/bmn_400x100_2x8_9e_activitynet_feature_mmaction_clip.py
- configs/localization/bmn/bmn_400x100_2x8_9e_activitynet_feature_mmaction_video.py
- configs/localization/bmn/metafile.yml
> [Fix] metafile.yml in BMN

- .github/workflows/build.yml
fix pycocotools install fail 
modify CI build.yml
> [Fix] pycocotools install fail 

- docs/en/user_guides/2_data_prepare.md
> [Docs] add data prepare doc

- docs/en/index.rst
- docs/en/overview.md
\## Modification
delete overview.
> [Docs] delete overview

- docs/en/user_guides/4_train_test.md
- tools/slurm_train.sh
> [Doc] add train_test.md

- tools/analysis_tools/report_accuracy.py
refactor fuse score test in report_accuracy.py
> [Refactor] refactor fuse score test 

- docs/en/user_guides/useful_tools.md
> [Doc] add useful_tools doc

- docs/en/notes/faq.md
> [Doc] add faq doc

- docs/en/migration.md
> [Doc] add migration doc

- docs/en/user_guides/index.rst
> [Docs] modify index.rst

- docs/en/user_guides/visualization.md
- mmaction/engine/hooks/__init__.py
- mmaction/engine/hooks/visualization_hook.py
> [Refactor] Add visualization hooks and docs.

- mmaction/models/data_preprocessors/data_preprocessor.py
- mmaction/models/heads/base.py
- mmaction/models/necks/tpn.py
- mmaction/models/roi_heads/roi_head.py
DataPreprocessor return a dict now.
modify function signature `batch_data_samples` to `data_samples`
> [Fix] modify data_preprocessor

- configs/_base_/models/tin_r50.py
- configs/recognition/tin/tin_r50_1x1x8_40e_sthv1_rgb.py
- configs/recognition/tin/tin_r50_1x1x8_40e_sthv2_rgb.py
- configs/recognition/tin/tin_tsm_finetune_r50_1x1x8_50e_kinetics400_rgb.py
- mmaction/models/backbones/resnet_tin.py
- mmaction/models/backbones/resnet_tsm.py
fix TIN model and related config files
> [Fix] fix tin model and config

- mmaction/engine/hooks/visualization_hook.py
> [Fix] Fix import bug in visualizer hook

- docs/en/conf.py
- docs/en/index.rst
- docs/en/merge_docs.sh
> [Fix] fix model zoo

- README.md
> [Refactor] Update readme

- docs/en/get_started.md
> [Refactor] fix get started

- docs/en/notes/changelog.md
Add change logs of previous versions and also v1.0.0rc
2. …
> [Doc] add back changelog.md

- .readthedocs.yml
> [Doc] support export pdf doc

- configs/skeleton/posec3d/README.md
- configs/skeleton/posec3d/metafile.yml
fix posec3d metafile and readme.
> [Fix] fix posec3d metafile and readme

- configs/recognition/tin/tin_imagenet-pretrained-r50_8xb6-1x1x8-40e_sthv1-rgb.py
- tools/slurm_train.sh
fix typo in TIN config and slurm_train
> [Fix] fix typo in TIN config and slurm_train

- docs/install.md
Fix link for Pillow-SIMD on installation docs.
No.
> Fix link for Pillow-SIMD

- .circleci/config.yml
- .circleci/docker/Dockerfile
- .circleci/scripts/get_mmcv_var.sh
- .circleci/test.yml
- docs/install.md
- requirements/optional.txt
> [CI] add circle ci for master

- README.md
> [Docs] Fix typo in `README.md`

- docs/en/migration.md
[Doc] fix typo in migration doc
> [Doc] fix typo in migration doc

- docs/en/user_guides/2_data_prepare.md
[Doc] fix link in data_prepare.md
> [Doc] fix link in data_prepare.md

- .circleci/config.yml
> [Fix] fix typo in circleCI

- tests/models/localizers/test_bmn.py
- tests/models/localizers/test_pem.py
- tests/models/localizers/test_tem.py
> [Fix] fix ut for bmn and bsn

- configs/recognition/tin/tin_imagenet-pretrained-r50_8xb6-1x1x8-40e_sthv1-rgb.py
- configs/recognition/tin/tin_imagenet-pretrained-r50_8xb6-1x1x8-40e_sthv2-rgb.py
- mmaction/models/backbones/resnet_tin.py
- mmaction/models/backbones/resnet_tsm.py
[Fix] fix wrong config of warmup schedule in TIN config
[Fix] fix bug and typo in TIN model
> [Fix] fix tin model

- .pre-commit-config.yaml
> Upgrade pre commit hooks in master

- .circleci/test.yml
- .github/workflows/merge_stage_test.yml
- .github/workflows/pr_stage_test.yml
- requirements/optional.txt
- tests/models/recognizers/test_recognizer2d.py
[CI] fix timm related bug for dev-1.x
> [CI] fix timm related bug for dev-1.x

- mmaction/__init__.py
> [Fix] update mmengine version restriction

- README.md
- docs/en/notes/changelog.md
- mmaction/version.py
> [Bump-ver] Bump version v1.0.0rc1

- .owners.yml
> [Enhance] Add openmmlab-bot configuation for automatic issue assigning

- requirements/optional.txt
- tools/analysis_tools/get_flops.py
Update Get flops tool.
no.
```shell
python tools/analysis_tools/get_flops.py configs/recognition/swin/swin-tiny_p244-w877-in1k-pre_8xb8-amp-32x2x1-30e_kinetics400-rgb.py --shape 1 3 32 224 224
```
Basically align with the paper results:
> [Refactor] Refactor flops params tool

- .owners.yml
> [Fix] Update openmmlab-bot config

- README.md
- README_zh-CN.md
> [doc] add v1.x intro in readme

- configs/recognition/c2d/metafile.yml
- tools/analysis_tools/report_accuracy.py
- tools/slurm_train.sh
fix `tools/analysis_tools/report_accuracy.py` and `tools/slurm_train.sh`.
1. Pre-commit or other linting tools …
> [Fix] Fix tools and mim error

- README.md
- configs/recognition/videomae/README.md
This PR updates README.md in VideoMAE.
> [Docs] Update VideoMAE in README.md

- README.md
- README_zh-CN.md
Add a blank line to normally visualize the header, and update some links.
Add a blank line to normally visualize the header, and update some links.
> [Docs] Update README.md and README_zh-CN.md

- README.md
> [Docs] Add VideoMAE  to MODEL_ZOO

- docs/en/user_guides/4_train_test.md
- tools/dist_test.sh
- tools/dist_train.sh
- tools/test.py
Refactor `4_train_test.md` and remove `--out` in `test.py`.
> [Docs] Refactor `4_train_test.md`

- mmaction/__init__.py
> [Imrpove] update mmcv maximum version to 1.8.0

- docs/en/user_guides/1_config.md
> [Docs] Refactor `1_config.md`

- configs/_base_/models/tsn_r50.py
- mmaction/datasets/transforms/formatting.py
- mmaction/models/heads/base.py
- mmaction/models/recognizers/base.py
- tests/models/recognizers/test_recognizer3d.py
[fix] fix multiple crop inference, now support save mutli scores of crops
> [Fix] Fix multi-view inference

- docker/Dockerfile
> Fix Dockerfile build Error

- tools/data/skeleton/gen_ntu_rgbd_raw.py
> [Fix] fix `gen_ntu_rgbd_raw.py`

- mmaction/models/backbones/swin.py
- mmaction/models/backbones/vit_mae.py
- mmaction/models/recognizers/base.py
- tests/models/recognizers/test_recognizer2d.py
[Improvement] support init_cfg for Swin and ViTMAE
> [Improve] support init_cfg for Swin and ViTMAE

- README.md
- tools/data/jester/README.md
- tools/data/jester/README_zh-CN.md
- tools/data/sthv1/README.md
- tools/data/sthv1/README_zh-CN.md
- tools/data/sthv2/README.md
- tools/data/sthv2/README_zh-CN.md
[doc] fix sth-sth and jester dataset link
> [Doc] fix sth-sth and jester dataset link

- README.md
> [Doc] add mvit in readme

- demo/demo.py
- mmaction/utils/gradcam_utils.py
[fix] fix demo bug, and gradcam bug in some cases
> [fix] fix a bug trigger by importing decord

- .circleci/test.yml
- configs/detection/ava_kinetics/slowonly_k700-pre-r50_8xb8-16x4x1-10e-tricks_ava-kinetics-rgb.py
[ci] update CI maximum torch version to 1.13.0
> [ci] update CI maximum torch version to 1.13.0

- README.md
#2113  break some critical links
> [Doc] Update EN README links for new doc structure

- tools/analysis_tools/check_videos.py
[fix]  fix check_videos.py and acclerate for large dataset(ie. k400)
> [fix]  fix check videos tool

- demo/visualize_heatmap_volume.ipynb
[Fix] fix bug in visualzie heatmap demo
> [Fix] fix bug in visualize heatmap demo

- tools/deployment/export_onnx_stdet.py
- tools/deployment/export_stdet.py
Simple implementation of spatial temporal detection model exporting to onnx.
> [Feature] export spatial temporal detection model to onnx

- .circleci/test.yml
- .github/workflows/merge_stage_test.yml
- README.md
- docs/en/get_started.md
- docs/en/notes/changelog.md
- docs/zh_cn/get_started.md
- mmaction/__init__.py
- mmaction/version.py
- setup.py
> Bump version to 1.0.0rc2

- mmaction/datasets/activitynet_dataset.py
- mmaction/datasets/ava_dataset.py
- mmaction/datasets/pose_dataset.py
- mmaction/datasets/rawframe_dataset.py
- mmaction/datasets/video_dataset.py
[Enhance] support  load data list from multi-backend
> [Enhance] support  load data list from multi-backend

- docs/zh_cn/user_guides/1_config.md
Translate 1_config.md
OpenMMLab Code Camp 
4. The …
> [CodeCamp #154] Translate 1_config.md

- demo/demo_skeleton.py
- mmaction/apis/inference.py
Fix issue #2202 
check whether the arg `pretrained` is in `config.model.backbone`.
> [Fix] Fix bug in demo_skeleton.py

- README.md
- docs/en/notes/changelog.md
- mmaction/version.py
> Bump version 1.0.0rc3

- README.md
[Fix] fix contrituting link in readme
> [Fix] fix contrituting link in readme

- README.md
> [Doc] Add twitter discord medium youtube link

- docs/en/get_started.md
- docs/zh_cn/get_started.md
[Doc] add instructions to install mmdet and mmpose
> [Doc] add instructions to install mmdet and mmpose

- .pre-commit-config.yaml
> [Fix] Fix isort

- demo/demo_spatiotemporal_det.py
- demo/demo_spatiotemporal_det_onnx.py
- mmaction/datasets/transforms/pose_transforms.py
- mmaction/evaluation/functional/accuracy.py
- mmaction/evaluation/functional/ava_evaluation/metrics.py
- mmaction/evaluation/functional/eval_detection.py
- tests/evaluation/metrics/test_metric_utils.py
- tools/data/activitynet/process_annotations.py
https://github.com/open-mmlab/mmaction2/issues/2145.
Fix deprecated aliases in Numpy v1.2.0+. https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations
> [Fix] Fix deprecated aliases

- demo/README.md
- demo/demo_skeleton.py
- demo/demo_spatiotemporal_det.py
- demo/demo_spatiotemporal_det_onnx.py
- mmaction/utils/misc.py
- tests/utils/test_misc.py
[Enhance] use tmpfile to avoid remaining tmp directory when demo break
> [Enhance] use tmpfile to avoid remaining tmp directory when demo break

- .circleci/test.yml
- .pre-commit-config.yaml
- docs/en/install.md
- docs/zh_cn/install.md
- setup.py
[fix] update ci config for master
> [fix] update ci config for master

- .gitignore
- docs/en/notes/contribution_guide.md
- projects/README.md
- projects/example_project/README.md
- projects/example_project/configs/examplenet_r50-in1k-pre_8xb32-1x1x3-100e_kinetics400-rgb.py
- projects/example_project/models/__init__.py
- projects/example_project/models/example_net.py
In this PR, we introduce a new `projects` folder in MMAction2. The `projects` is used to support some new algorithms and community projects efficiently. In this folder, we won't be strict with code style and other requirements. And some projects can also be moved to the core package after refactoring.
> [Project] Add Example project

- .circleci/test.yml
- docs/en/conf.py
- requirements/build.txt
> Add numpy minimum version requirement

- projects/ctrgcn/README.md
- projects/ctrgcn/configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py
- projects/ctrgcn/configs/ctrgcn_8xb16-joint-u100-80e_ntu60-xsub-keypoint-3d.py
- projects/ctrgcn/models/__init__.py
- projects/ctrgcn/models/ctrgcn.py
- projects/ctrgcn/models/ctrgcn_utils.py
> [Project] Add CTRGCN project

- .readthedocs.yml
- tests/models/recognizers/test_recognizer2d.py
> [doc] cancel compile pdf docs

- README.md
- README_zh-CN.md
> [Docs] Add the docs about readme_zh-CN.md

- README.md
- README_zh-CN.md
[doc] add social networking links
> [Doc] add social networking links (master)

- README.md
- README_zh-CN.md
[Doc]: Add more social networking links(dev-1.x)
> [Doc]: Add more social networking links(dev-1.x)

- tools/misc/clip_feature_extraction.py
- tools/test.py
- tools/train.py
[Fix] Fix accepting an unexpected argument local-rank in PyTorch 2.0 for 1.x branch
> [Fix] Fix accepting an unexpected argument local-rank in PyTorch 2.0 for 1.x branch

- tools/misc/clip_feature_extraction.py
- tools/test.py
- tools/train.py
[Fix] Fix accepting an unexpected argument local-rank in PyTorch 2.0
> [Fix] Fix accepting an unexpected argument local-rank in PyTorch 2.0

- tests/models/recognizers/test_recognizer2d.py
- tools/data/kinetics/README.md
- tools/data/kinetics/README_zh-CN.md
[doc] add opendatalab kinetics link
> [doc] add opendatalab kinetics link

- .circleci/test.yml
- configs/recognition/tsm/tsm_imagenet-pretrained-mobilenetv2_8xb16-1x1x8-50e_kinetics400-rgb.py
- mmaction/models/backbones/mobilenet_v2_tsm.py
- mmaction/models/backbones/resnet_tsm.py
- tests/models/recognizers/test_recognizer2d.py
> [Fix] fix mobilenetv2_tsm

- .github/workflows/merge_stage_test.yml
- .github/workflows/pr_stage_test.yml
[Fix] update aciton docker image to ubuntu-22.04
> [Fix] update action docker image to ubuntu-22.04

- .circleci/test.yml
- .github/workflows/build.yml
> [fix] fix ci (master)

- .github/workflows/merge_stage_test.yml
> [Fix] fix merge stage test

- docs/en/guide_to_framework.md
- docs/en/index.rst
> [Docs] Add 20 Minutes Guide

- mmaction/registry.py
- mmaction/visualization/action_visualizer.py
[fix] fix channel order when show video
> [fix] fix channel order when show video

- configs/detection/lfb/README.md
- configs/detection/lfb/metafile.yml
- configs/detection/lfb/slowonly-lfb-infer_r50_ava21-rgb.py
- configs/detection/lfb/slowonly-lfb-nl_kinetics400-pretrained-r50_8xb12-4x16x1-20e_ava21-rgb.py
- mmaction/models/roi_heads/shared_heads/lfb.py
1. Speed up feature bank sampling
2. Add a missing config for inferring long term feature banks.
3.  Re-test the checkpoint.
> [Refactor] speed up LFB training

- mmaction/evaluation/metrics/__init__.py
- mmaction/evaluation/metrics/acc_metric.py
- mmaction/structures/action_data_sample.py
- tests/evaluation/metrics/test_acc_metric.py
- tests/models/recognizers/test_recognizer2d.py
- tools/analysis_tools/confusion_matrix.py
[Feat] support calculate confusion matrix
> [Feat] support calculate confusion matrix

- README.md
- docs/en/advanced_guides/customize_optimizer.md
- docs/en/advanced_guides/customize_pipeline.md
> [Doc] for README, optimizers and data pipeline

- .circleci/test.yml
> [CI] fix circleci config

- .circleci/test.yml
- mmaction/datasets/transforms/pose_transforms.py
> [CI] update circle ci

- .circleci/test.yml
- mmaction/datasets/transforms/pose_transforms.py
> [CI] fix circle CI

- .circleci/test.yml
- .github/workflows/build.yml
[CI] upgrade upstream lib version in circle CI
> [CI] Upgrade upstream lib version in circle CI

- README.md
[Doc] Fix model links in README
> [Doc] Fix model links in README

- configs/recognition/tsn/tsn_imagenet-pretrained-r50_8xb32-1x1x3-100e_kinetics400-rgb.py
- tests/models/utils/test_gradcam.py
[Fix] Restore the wrongly modified config
> [Fix] Restore the wrongly modified config

- README.md
- README_zh-CN.md
> [Doc] Fix readme links

- mmaction/__init__.py
> [Update] Update version requirements

- README.md
> [Doc] update readme

- demo/mmaction2_tutorial.ipynb
> [Fix] Fix colab tutorial

- demo/mmaction2_tutorial.ipynb
[Fix] update colab link in tutorial
> [Fix] update colab link in tutorial

- .github/workflows/pr_stage_test.yml
> [CI] fix github ci

- .github/workflows/pr_stage_test.yml
> [CI] fix github ci (main)

- .github/ISSUE_TEMPLATE/1-bug-report.yml
> [Fix] Fix issue template

- configs/detection/lfb/slowonly-lfb_ava-pretrained-r50_infer-4x16x1_ava21-rgb.py
- configs/recognition/uniformerv2/uniformerv2-large-p16-res336_clip-kinetics710-kinetics-k400-pre_u8_mitv1-rgb.py
- configs/recognition/videomae/vit-large-p16_videomae-k400-pre_16x4x1_kinetics-400.py
> [Fix] fix bug in config files

- README.md
- README_zh-CN.md
- requirements/docs.txt
> [Doc] Update repo list

- .circleci/test.yml
- mmaction/datasets/transforms/wrappers.py
[Fix] Fix incompatibility of ImgAug and latest Numpy
> [Fix] Fix incompatibility of ImgAug and latest Numpy

- docker/Dockerfile
[Fix] Update branch in dockerfile
> [Fix] Update branch in dockerfile

- projects/ctrgcn/README.md
- projects/msg3d/README.md
update `MSG3D` and `CTRGCN` projects.
> [Update] update `MSG3D` and `CTRGCN` projects

- mmaction/models/utils/blending_utils.py
- tests/models/utils/test_blending_utils.py
[fix] Fix batch blending bug when using multi-label classification
> [fix] Fix batch blending bug when use multi-label classification

- .circleci/config.yml
- .circleci/test.yml
- .github/workflows/build.yml
- mmaction/datasets/pipelines/augmentations.py
- mmaction/models/recognizers/base.py
> [Fix] fix auto_fp16

- demo/demo_configs/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person.py
- tools/data/skeleton/ntu_pose_extraction.py
[Fix] Align num_persons among frames and filter frame without det result
> [Fix] Fix ntu pose extraction

- docs/en/index.rst
- docs/en/user_guides/finetune.md
- docs/en/user_guides/train_test.md
> [Doc] add finetune doc

- mmaction/visualization/action_visualizer.py
- tools/analysis_tools/report_map.py
- tools/data/activitynet/convert_proposal_format.py
- tools/data/activitynet/download.py
- tools/data/ava/download_videos_parallel.py
- tools/data/hvu/download.py
- tools/data/hvu/generate_file_list.py
- tools/data/hvu/generate_sub_file_list.py
- tools/data/hvu/parse_tag_list.py
- tools/data/omnisource/trim_raw_video.py
[Fix] Update outdated dependencies of mmcv
> [Fix] Update outdated dependencies of mmcv

- docs/en/get_started/faq.md
> [Doc] Update faq doc

- demo/README.md
- docs/en/tutorials/1_config.md
- docs/zh_cn/tutorials/1_config.md
[Doc] Fix doc of Video Structuralize Demo
> [Doc] Fix doc of Video Structuralize Demo

- configs/detection/videomae/README.md
- configs/detection/videomae/metafile.yml
- configs/detection/videomae/vit-base-p16_videomae-k400-pre_8xb8-16x4x1-20e-adamw_ava-kinetics-rgb.py
- configs/detection/videomae/vit-large-p16_videomae-k400-pre_8xb8-16x4x1-20e-adamw_ava-kinetics-rgb.py
- mmaction/engine/optimizers/layer_decay_optim_wrapper_constructor.py
- mmaction/models/backbones/vit_mae.py
> [Feature] support videomae stdet

- README.md
- README_zh-CN.md
To add Chinese version document of README.md into this project
The corresponding Chinese version of the document [README_zh-CN.md](https://github.com/open-mmlab/mmaction2/blob/main/README_zh-CN.md) was updated.
No!
NA
> Translate README.md to Chinese

- .circleci/test.yml
- .github/workflows/merge_stage_test.yml
- docker/Dockerfile
- docs/en/get_started/installation.md
- docs/zh_cn/get_started/installation.md
- mmaction/datasets/transforms/pose_transforms.py
[Fix] Update minimum PyTorch version to 1.8.1
> [Fix] Update minimum PyTorch version to 1.8.1

- MANIFEST.in
- dataset-index.yml
- docs/en/conf.py
- setup.py
- tools/data/diving48/README.md
- tools/data/diving48/README_zh-CN.md
- tools/data/diving48/preprocess.sh
- tools/data/kinetics/README.md
- tools/data/kinetics/README_zh-CN.md
- tools/data/kinetics/preprocess_k400.sh
- tools/data/kinetics/preprocess_k600.sh
- tools/data/kinetics/preprocess_k700.sh
- tools/data/kinetics710/README.md
- tools/data/kinetics710/README_zh-CN.md
- tools/data/sthv2/README.md
- tools/data/sthv2/README_zh-CN.md
- tools/data/sthv2/preprocss.sh
[feat] Add dataset index and scripts to support mim download dataset
Add  dataset-index.yml, which provides info to download datasets from OpenDataLab
Add preprocess script to process data into a useable format
> [feat] Add dataset index and scripts to support mim download dataset

- .circleci/test.yml
- .github/workflows/merge_stage_test.yml
> [Fix] fix CI

- configs/localization/bsn/metafile.yml
[Fix] Fix illegal multiple config files in bsn metafile
> [Fix] Fix illegal multiple config files in bsn metafile

- docs/en/user_guides/finetune.md
Fixing a typo in the documentation.
Fixing a typo of the word "Dataset". It was changed from "datast" to "dataset".
No.
N/A
4. The documentation should be modified accordingly, like …
> [Docs] Fixing typo in documentation

- README_zh-CN.md
- projects/actionclip/README.md
1 README_zh-Cn.MD Installation link error 
2 I think this location is missing 'import torch' in actionclip. The original code I ran was in 'device="cuda" if torch. cuda. is_ An error will be reported in the 'available () else' 'line
> [Docs] Modify_readme

- configs/recognition/swin/README_zh-CN.md
- configs/recognition/videomae/README_zh-CN.md
> [MMSIG380]Add README_zh-CN.md

- docs/en/user_guides/prepare_dataset.md
- docs/zh_cn/user_guides/prepare_dataset.md
Add audio data in data preparation
> [Docs] Update Audio Docs

- projects/gesture_recognition/README.md
Fix gesture recognition readme
> [Doc] Fix gesture recognition readme

- tests/models/backbones/test_resnet_audio.py
> [Fix] Fix resnet audio ut
