requirements/runtime.txt

[mmcv-nighty](https://pypi.org/project/mmcv-nightly/) is the old version of mmcv.

Use mmcv instead of mmcv-nighty

---

docs/data_preparation.md
docs/getting_started.md
tools/data/activitynet/preparing_activitynet.md
tools/data/build_rawframes.py
tools/data/kinetics400/extract_rgb_frames_opencv.sh
tools/data/kinetics400/preparing_kinetics400.md
tools/data/mit/extract_rgb_frames_opencv.sh
tools/data/mit/preparing_mit.md
tools/data/mmit/extract_rgb_frames_opencv.sh
tools/data/mmit/preparing_mmit.md
tools/data/sthv1/extract_rgb_frames_opencv.sh
tools/data/sthv1/preparing_sthv1.md
tools/data/sthv2/extract_rgb_frames_opencv.sh
tools/data/sthv2/preparing_sthv2.md
tools/data/thumos14/extract_rgb_frames_opencv.sh
tools/data/thumos14/preparing_thumos14.md
tools/data/ucf101/extract_rgb_frames_opencv.sh
tools/data/ucf101/preparing_ucf101.md

1. Add `--use-opencv` args in `build_rawframes.py` to extract rgb rawframes by OpenCV instead of denseflow
2. Rename sth to MMACTION2

Extract rgb frames without denseflow

---

configs/recognition/i3d/i3d_r50_video_32x2x1_100e_kinetics400_rgb.py
configs/recognition/i3d/i3d_r50_video_inference_32x2x1_100e_kinetics400_rgb.py
configs/recognition/r2plus1d/r2plus1d_r34_video_8x8x1_180e_kinetics400_rgb.py
configs/recognition/r2plus1d/r2plus1d_r34_video_inference_8x8x1_180e_kinetics400_rgb.py
configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py
configs/recognition/slowfast/slowfast_r50_video_inference_4x16x1_256e_kinetics400_rgb.py
configs/recognition/slowonly/slowonly_r50_video_4x16x1_256e_kinetics400_rgb.py
configs/recognition/slowonly/slowonly_r50_video_inference_4x16x1_256e_kinetics400_rgb.py
configs/recognition/tsm/tsm_r50_video_1x1x8_100e_kinetics400_rgb.py
configs/recognition/tsm/tsm_r50_video_inference_1x1x8_100e_kinetics400_rgb.py
configs/recognition/tsn/tsn_r50_video_1x1x8_100e_kinetics400_rgb.py
configs/recognition/tsn/tsn_r50_video_dense_1x1x8_100e_kinetics400_rgb.py
configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py
mmaction/datasets/pipelines/loading.py

`start_index` is used in `SampleFrames` to specify a start index for frames in consideration of different filename format in rawframes. But when taking videos as input, the `start_index` should be set to 0, since the frames loaded from videos are stored in a list, which counts from 0.

[Bug Fix] Fix a bug caused by start_index when using videos

---

configs/recognition/r2plus1d/r2plus1d_r34_32x2x1_180e_kinetics400_rgb.py
configs/recognition/r2plus1d/r2plus1d_r34_8x8x1_180e_kinetics400_rgb.py
configs/recognition/r2plus1d/r2plus1d_r34_video_8x8x1_180e_kinetics400_rgb.py
configs/recognition/slowfast/slowfast_r50_4x16x1_256e_kinetics400_rgb.py
configs/recognition/slowfast/slowfast_r50_8x8x1_256e_kinetics400_rgb.py
configs/recognition/slowfast/slowfast_r50_video_4x16x1_256e_kinetics400_rgb.py
configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_flow.py
configs/recognition/slowonly/slowonly_r50_4x16x1_256e_kinetics400_rgb.py
configs/recognition/slowonly/slowonly_r50_8x8x1_256e_kinetics400_flow.py
configs/recognition/slowonly/slowonly_r50_8x8x1_256e_kinetics400_rgb.py
configs/recognition/slowonly/slowonly_r50_video_4x16x1_256e_kinetics400_rgb.py
docs/config.md

Name bug seems exists. Config not work with mmcv 1.0.3

Fix name bug.

---

configs/recognition/tsn/tsn_r50_inference_1x1x3_100e_kinetics400_rgb.py
demo/demo.py
docs/getting_started.md
mmaction/apis/inference.py

* Support rawframe inference in demo
* Raise Error when dataset type is not consist with the input type. (rawframe VS video)
* Polish demo scripts and docs

Support rawframe inference in demo and polish scripts and docs

---

mmaction/datasets/pipelines/loading.py
mmaction/datasets/rawframe_dataset.py
tests/data/frame_test_list_multi_label.txt
tests/data/frame_test_list_with_offset.txt
tests/test_data/test_dataset.py
tests/test_data/test_loading.py

add feature 'with offset' for rawframe dataset, need this feature to train recognition models on untrimmed datasets

Add feature `with_offset` for rawframe dataset

---

tools/data/parse_file_list.py

1. list.sort()  function will return nothing, so the `class_list` will be none. Use sorted() instead.
2. The offical HMDB51 annotations file is [action]_test_split[1-3].txt  corresponding to three splits reported in the paper.

Fix the bug of generating HMDB51 class index file.

---

tools/data/build_file_list.py
tools/data/parse_file_list.py

This PR polishes data preparation codes and has tested it to ensure its Correctness.

Polish data preparation codes

---

mmaction/datasets/pipelines/loading.py
tests/test_data/test_loading.py

This pr uses `xxInit()` method to get total_frames, it is a better way to get the total frames number for video.

use `xxInit()` method to get total_frames

---

tools/slurm_train.sh
tools/train.py

The `args.work_dir` will never be None, it will only be `''` an empty str. When training without specific work_dir, it results in lots of logs and ckpts saved in $MMACTION2_HOME.

Fix bug in work_dir.

---

docs/install.md

When I was reading the install.md , I was confused by the unclear command example. So I changed it to a more concrete example.
This is my first pull request, so I apologize if there are any mistakes.
best.

make pip command example more concrete

---

mmaction/models/backbones/resnet3d_csn.py
tests/test_models/test_backbone.py

This PR fixes bug, which affects the testing, in `def train(self, mode=True):` in CSN. The modification has been well tested.

Bug fix in CSN mode setting

---

tests/test_data/test_dataset.py

This PR resolves a random failure for unittest caused by out of bound in `BaseDataset`.

Fix random unittest failure for BaseDataset

---

mmaction/datasets/base.py
mmaction/datasets/rawframe_dataset.py
mmaction/datasets/video_dataset.py
tools/data/anno_txt2json.py
tools/data/build_file_list.py

Support the new json annotation format, which is more scalable than txt files: 
1. You can use the command `python tools/data/anno_txt2json.py annotation.txt` to convert it from txt to json.
2. The dataset can automatically detect json annotation list and load it.
3. When the repo decides to switch from txt to json, just change the default option of output_format in `build_file_list.py`  to 'json'

Support Json annotations

---

README.md
docs/changelog.md

This PR initializes changelog.md docs for v0.5.0 and v0.6.0. Any import changes should be categorized (I suggest using [tag] in each PR for convenience) and logged in this this PR. @kennymckormick @SuX97 @innerlee @JoannaLXY @tony2016uestc

Initialize changelog.md for v0.5.0 and v0.6.0

---

mmaction/models/backbones/resnet_tin.py

This PR adds `try-except` in `tin_shift` importing for users who do not need `TIN`.

Add try-except in tin_shift importing

---

mmaction/models/backbones/resnet.py
mmaction/models/backbones/resnet3d.py
tests/test_models/test_backbone.py

Actually, the default value of norm_eval should be False. 
Thus if a user forgets to set this arg, the training is still OK.

Change default value of `norm_eval` to False

---

README.md
docs/changelog.md
docs/tutorials/export_model.md
requirements/optional.txt
setup.cfg
tools/torch2onnx.py

ONNX exporting support.

---

docs/changelog.md
docs/tutorials/new_modules.md

Add customized updater tutorial

---

docs/install.md
requirements/optional.txt

Decord has new release for [pip package](https://github.com/dmlc/decord/releases), but 0.4.0 is default (without @innerlee 's fix). This update may avoid further explanation for users.

Update the requirement for decord.

---

docs/changelog.md
docs/tutorials/customize_runtime.md
mmaction/apis/train.py
mmaction/core/evaluation/__init__.py
mmaction/core/evaluation/eval_hooks.py
tests/test_eval_hook.py
tools/analysis/eval_metric.py

1. Add `start` argument in `xxEvalHook` to indicate the start time for evaluation
2. Add prefix `Epoch` to indicate the current `EvalHook` is based on epochs

[Feature] Add init_eval to evaluation hook

---

configs/recognition_audio/resnet/README.md
docs/changelog.md

Update the audio fusion result with a better tsn-f3 result.

---

mmaction/core/lr/__init__.py

Let's say you want to install mmaction2 using `python setup.py install` or `pip install git+https://github.com/open-mmlab/mmaction2.git`
This install is missing a file as shown below
```console
(venv) sebastien@linker:<path_to_your_repo (not mmaction)>$ diff -r -x __pycache__ venv/lib/python3.7/site-packages/mmaction2-0.8.0-py3.7.egg/mmaction/ <path_to_cloned_mmaction2>/mmaction
Only in <path_to_cloned_mmaction2>/mmaction/core: lr
```
This PR is fixing this

Fixed install

---

docs/changelog.md
mmaction/apis/test.py

ref: https://github.com/open-mmlab/mmdetection/pull/4017

[Fix] Fix multi-node dist test

---

docs/changelog.md
mmaction/datasets/pipelines/loading.py

This PR corrects https://github.com/open-mmlab/mmaction2/pull/354.

[Fix] Fix for `tmp_folder` in `OpenCVInit`

---

demo/long_video_demo.py

This PR fix 2 potential issue in long_video_demo.py
1. The last of some videos will be decoded as None in OpenCV. When it is the case, demo will skip it.
2. Popleft only once for keeping img shape.

Fix potential issue in long_video_demo.py

---

tools/data/kinetics/preparing_kinetics.md
tools/data/kinetics/rename_classnames.sh

Previous `rename_classnames.sh` and `detox` can rename the
`(` and `)` to `-`, which is not desirable. [#374](https://github.com/open-mmlab/mmaction2/issues/374#issue-749310860)

fix rename kinetics classnames bug

---

configs/recognition/tsm/README.md
configs/recognition/tsm/tsm_nl_dot_product_r50_1x1x8_50e_kinetics400_rgb.py
configs/recognition/tsm/tsm_nl_embedded_gaussian_r50_1x1x8_50e_kinetics400_rgb.py
configs/recognition/tsm/tsm_nl_gaussian_r50_1x1x8_50e_kinetics400_rgb.py
configs/recognition/tsm/tsm_r101_1x1x8_50e_sthv1_rgb.py
configs/recognition/tsm/tsm_r101_1x1x8_50e_sthv2_rgb.py
configs/recognition/tsm/tsm_r50_1x1x16_50e_kinetics400_rgb.py
configs/recognition/tsm/tsm_r50_1x1x16_50e_sthv1_rgb.py
configs/recognition/tsm/tsm_r50_1x1x16_50e_sthv2_rgb.py
configs/recognition/tsm/tsm_r50_1x1x8_50e_kinetics400_rgb.py
configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv1_rgb.py
configs/recognition/tsm/tsm_r50_1x1x8_50e_sthv2_rgb.py
configs/recognition/tsm/tsm_r50_dense_1x1x8_100e_kinetics400_rgb.py
configs/recognition/tsm/tsm_r50_video_1x1x8_50e_kinetics400_rgb.py
configs/recognition/tsm/tsm_temporal_pool_r50_1x1x8_50e_kinetics400_rgb.py
demo/README.md
demo/long_video_demo.py
docs/changelog.md
mmaction/datasets/pipelines/loading.py
mmaction/models/heads/tsm_head.py
mmaction/models/recognizers/base.py
mmaction/models/recognizers/recognizer2d.py
mmaction/models/recognizers/recognizer3d.py
tests/test_gradcam.py
tests/test_models/test_recognizers.py

+ Describe bug: Try to run `tools/test.py` with TSM model and `DenseSampleFrames` with default [config](https://github.com/open-mmlab/mmaction2/blob/master/configs/recognition/tsm/tsm_r50_dense_1x1x8_100e_kinetics400_rgb.py) and [checkpoint](https://download.openmmlab.com/mmaction/recognition/tsm/tsm_r50_dense_1x1x8_100e_kinetics400_rgb/tsm_r50_dense_1x1x8_100e_kinetics400_rgb_20200626-91a54551.pth), but failed. 
+ Solution: Finally I find that, when using TSM models, we HAVE TO SET `test_cfg['test_crops']` MANUALLY to get correct results.
+ Thoughts: Maybe we should find a way to set `test_crops` automatically, not manually, like `Recognizer3D` models?
+ [x] In order to let users to have better understanding about test crops, add more docs about this.
+ [x] Update TSM DenseSampleFrames …

[Improvement] Update docs about test crops.

---

tests/test_data/test_loading.py

add unittest on repr for LoadHVULabel and SampleFrames in loading.py

---

mmaction/apis/train.py
tools/test.py

This PR sets default batch_size of evaluation and testing as 1 to avoid OOM and manual config changes in most cases, since it used the training `batch_size` as default when `videos_per_gpu=cfg.data.get('videos_per_gpu', 2)`

[Improvement] set default batch_size of evaluation and testing to 1

---

demo/webcam_demo.py

I implement single thread version of webcam demo, which is similar to `demo/long_video_demo.py`. Compared to `demo/webcam_demo.py`, I find that single thread version's CPU utility **significantly increased**, 100%-200%(`demo/webcam_demo.py`) to 500%-600%(single thread version).
After some debugging, I find the performance bottleneck are the codes bellow.
```python
while True:
if not pw.is_alive():
exit(0)
```
Cpu utility is copy from `top`. environment (i5 + 32G + 1080ti), cpu utility increases from `100%-200%` to `400%-500%`, gpu utility increases from 1% to 50%.
test webcam sample is from `demo/README.md`: 
```shell
python demo/webcam_demo.py configs/recognition/tsn/tsn_r50_video_inference_1x1x3_100e_kinetics400_rgb.py \
https://download.openmmlab.com/mmaction/recognition/tsn/tsn_r50_1x1 …
```

[Improvement] improve webcam demo cpu utility.

---

mmaction/models/recognizers/recognizer2d.py
mmaction/models/recognizers/recognizer3d.py
tests/test_models/test_recognizers.py

This PR fixes a bug when calling `dummy forward`(FLOPS calculation or onnx conversion), which used to skip the neck module.
Fixes #429

Fix dummy forward

---

docs/changelog.md
docs/stat.py
requirements/readthedocs.txt
setup.cfg

Signed-off-by: lizz <lizz@sensetime.com>

Titlecase in stats

---

tools/data/activitynet/download_videos.sh
tools/data/gym/environment.yml

fix some errors in download_video.sh
for activitynet, download.py relies on mmcv.
for gym, the virtual env name should be gym.

data_preprocess

---

docs/changelog.md
tools/test.py

This PR fixes potential bug when users do not assign parser args. For example, if a user does not assign `args.out` 
```python
output_config = dict(out=f'{work_dir}/results.json', output_format='json')
args.out = None
output_config = Config._merge_a_into_b(dict(out=args.out), output_config)
```
then, `output_config` in config files will be overwritten.

[Fix] Fix potential bug about output_config overwrite

---

docs/changelog.md
mmaction/core/evaluation/accuracy.py

This PR uses `np.bincount` to speed up confusion matrix calculation

[Improvement] speed up confusion matrix calculation

---

tools/data/kinetics/README.md

add dataset size of kinetics400

---

docs/tutorials/4_data_pipeline.md

add lazy ops docs

---

mmaction/models/backbones/resnet3d_slowfast.py

Quick add some explanation about the resampling in slowfast.

---

tools/data/kinetics/README.md

Easier way to download kinetics400 and kinetics700.

[Improvement] alternative way to download kinetics.

---

configs/detection/ava/slowfast_context_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py
configs/detection/ava/slowfast_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py
configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py
configs/detection/ava/slowonly_kinetics_pretrained_r101_8x8x1_20e_ava_rgb.py
configs/detection/ava/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py
configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py
configs/detection/ava/slowonly_omnisource_pretrained_r50_4x16x1_20e_ava_rgb.py
docs/changelog.md
mmaction/core/evaluation/ava_evaluation/object_detection_evaluation.py
mmaction/core/evaluation/eval_hooks.py
tests/test_accuracy.py
tests/test_data/test_ava_dataset.py

+ Description: When training ava dataset with default configs, no validaton results stored.
+ Multi-GPU
+ script: `tools/dist_train.sh configs/detection/ava/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py 8 --validate`
+ details: successfully run eval after every epoch, but `best.json` is not created in work dir.
+ single-gpu:
+ script: `python tools/train.py configs/detection/ava/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py --validate`
+ details: sucessfully run ava eval, but `TypeError` occured.
```
/ssd01/zhangyiyang/mmaction2_github/mmaction/core/evaluation/eval_hooks.py:176: UserWarning: The key indicator for evaluation is not included in evaluation result, please specify it in config file
warnings.warn('The key indicator for evaluation is not '
Traceback (most …
```

[Fix] fix a bug about validation of ava dataset

---

configs/recognition/i3d/i3d_r50_video_imgaug_32x2x1_100e_kinetics400_rgb.py
configs/recognition/tsn/tsn_r50_video_imgaug_1x1x8_100e_kinetics400_rgb.py
docs/changelog.md
mmaction/datasets/pipelines/__init__.py
mmaction/datasets/pipelines/augmentations.py
requirements/optional.txt
tests/test_data/test_augmentations.py

Support [imgaug](https://github.com/aleju/imgaug) in dataset pipeline.
+ TODO
+ [x] changelog & docs.
+ [x] tests.
Some of these codes are modified from [mmdet](https://github.com/open-mmlab/mmdetection/blob/482f60fe55c364e50e4fc4b50893a25d8cc261b0/mmdet/datasets/pipelines/transforms.py#L1191). 
Any suggestions about this PR?

[Feature] Support Imgaug for augmentations in the data pipeline.

---

tools/data/ava/extract_rgb_frames_ffmpeg.sh

`out_name` should be `"${OUT_DATA_DIR}/${video_name}/img_%05d.jpg"`, not `"${OUT_DATA_DIR}/${video_name}//${video_name}/img_%05d.jpg"`

[Fix] fix ava extract rgb frames script path error

---

configs/detection/ava/slowfast_context_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py
configs/detection/ava/slowfast_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py
configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py
configs/detection/ava/slowonly_kinetics_pretrained_r101_8x8x1_20e_ava_rgb.py
configs/detection/ava/slowonly_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py
configs/detection/ava/slowonly_omnisource_pretrained_r101_8x8x1_20e_ava_rgb.py
configs/detection/ava/slowonly_omnisource_pretrained_r50_4x16x1_20e_ava_rgb.py
docs/tutorials/7_customize_runtime.md
mmaction/apis/train.py
mmaction/core/evaluation/__init__.py
mmaction/core/evaluation/eval_hooks.py
mmaction/datasets/activitynet_dataset.py
mmaction/datasets/base.py
mmaction/datasets/hvu_dataset.py
mmaction/datasets/ssn_dataset.py
tests/test_runtime/test_eval_hook.py
tests/test_runtime/test_train.py
tools/analysis/eval_metric.py

This PR refactors EvalHook
1. Add by_epoch param to determine perform evaluation by epoch or by iteration.
2. Add automatically assign a compare key when users do not set one.
3. Save checkpoint by creating a symlink as well as record best info in runner hook meta
4. Refactor the code structure
Configs files need to be changed
1. Rename `EpochEvalHook` to `EvalHook`, `DistEpochEvalHook` to `DistEvalHook`.
2. Rename `key_indicator` to `save_best`.
For example, in `slowfast_kinetics_pretrained_r50_4x16x1_20e_ava_rgb.py` cfg file
from 
```python
evaluation = dict(interval=1, key_indicator='mAP@0.5IOU')
```
to
```python
evaluation = dict(interval=1, save_best='mAP@0.5IOU')
```
This Part may further be merged into `MMCV` or applied to other MM codebases.

[Refactor] refactor EvalHook

---

demo/demo_spatiotemporal_det.py
docs/changelog.md
mmaction/core/bbox/assigners/max_iou_assigner_ava.py
mmaction/core/evaluation/recall.py
mmaction/models/backbones/resnet3d.py
mmaction/models/backbones/resnet3d_slowfast.py
mmaction/models/backbones/resnet3d_slowonly.py
mmaction/models/backbones/resnet_tin.py
mmaction/models/builder.py
mmaction/models/heads/bbox_head.py
mmaction/models/heads/roi_head.py
mmaction/models/roi_extractors/single_straight3d.py
mmaction/utils/__init__.py
mmaction/utils/decorators.py
tests/test_utils/test_bbox.py
tests/test_utils/test_decorator.py

This PR removes dependency package warnings using `import_module_error_xxx` hooks

[Improvement] Remove dependency package warnings

---

mmaction/core/evaluation/eval_hooks.py
tests/test_runtime/test_eval_hook.py
tests/test_runtime/test_train.py

[Improvement] Modify default value of `save_best`

---

README.md
docs/install.md
mmaction/models/builder.py
requirements/optional.txt

[Improvement] Add warnings of uninstalling mmdet and supplementary documents

---

docs/changelog.md
mmaction/models/losses/cross_entropy_loss.py
tests/test_metrics/test_losses.py

Soft labels are required for data augmentation methods like mixup, cutmix, etc. For now, official `CrossEntropyLoss`  doesn't support soft labels.
+ If number of classes is 4.
+ Hard labels example: `[0, 1, 2]`
+ Corresponding soft labels are `[[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0]]`
+ Mixup/Cutmix may create soft labels like `[[0.8, 0.2, 0, 0], [0.1, 0.9, 0, 0], [0, 0, 0.6, 0.4]]`
+ It's difficult to get a proper name for this pr and related args.
+ `Sparse` is borrowed from TensorFlow and MXNet, TensorFlow has  `CategoricalCrossentropy`(accept non-sparse, one-hot like labels) and `SparseCategorialCrossentropy`(just like `CrossEntropyLoss` in pytorch).
+ BTW, **one-hot like labels** is more clear and meaningful for me.
+ For now, this pr detects loss type by the shape of label.
+ [x] …

[Improvement] Support soft label for CrossEntropyLoss

---

docs/changelog.md
mmaction/datasets/builder.py
mmaction/datasets/samplers/distributed_sampler.py

[Feature] Add seed option for sampler

---

mmaction/__init__.py
mmaction/version.py

1. Bump new version
2. upper `mmcv_minimum_version` due to https://github.com/open-mmlab/mmcv/pull/743

Bump version to v0.12.0

---

mmaction/core/evaluation/eval_hooks.py

I modified the eval_hook.py to support broadcast the buffer of batch_norm in rank 0 to other ranks, so as to ensure that the test results in the log can be consistent with individual test results with the saved checkpoint.

[Bug Fix] Add bn buffer sync in eval_hook

---

mmaction/models/recognizers/recognizer2d.py
tests/test_models/test_recognizers/test_recognizer2d.py

'loss_aux' got lost in losses, this PR adds it back together with related unittest.

[Bug] Add missing 'loss_aux' and related unittest

---

configs/_base_/models/bmn_400x100.py
configs/_base_/models/bsn_pem.py
configs/_base_/models/bsn_tem.py
tools/test.py

`train_cfg` and `test_cfg` are useless in bmn and bsn.
fix #662

Remove train test cfg in bmn and bsn

---

docs/changelog.md
mmaction/datasets/video_dataset.py
tests/data/annotations/video_test_list_multi_label.txt
tests/test_data/test_datasets/base.py
tests/test_data/test_datasets/test_video_dataset.py

Fix #722
One-hot label convertion should(and has been) take place in `prepare_train_frames/prepare_test_frames`, not in `load_annotations`, just like `RawframeDataset`

[Fix] Fix a bug about multi-class in VideoDataset

---

docs/changelog.md
docs/tutorials/6_export_model.md
docs/useful_tools.md
docs_zh_CN/tutorials/6_export_model.md
docs_zh_CN/useful_tools.md
mmaction/models/recognizers/recognizer2d.py
mmaction/models/recognizers/recognizer3d.py
tests/test_models/test_recognizers/test_recognizer2d.py
tests/test_models/test_recognizers/test_recognizer3d.py
tools/pytorch2onnx.py

Now the exported recognizer onnx model doesn't have a softmax layer. In order to get predictions in range `[0, 1]`, `--softmax` option is added to `pytorch2onnx.py`, to add a softmax layer at the end of recognizers.
```shell
python tools/pytorch2onnx.py $CONFIG_PATH $CHECKPOINT_PATH --shape $SHAPE --verify --softmax
```
+ [x] codes
+ [x] docs
+ [x] unittest
+ [x] changelog
Why does `forward_dummy` return a tuple `(outs, )` instead of `outs`?

[Improvement] Add softmax option for pytorch2onnx tool.

---

tools/data/ava/README.md
tools/data/ava/README_zh-CN.md

Now we only support raw frames for AVA dataset.

[Docs] Update AVA processing data README

---

docs/changelog.md
tests/test_utils/test_onnx.py
tools/pytorch2onnx.py

When `num_classes <= 4`, `pytorch_result[:, 4]` will raise index out of range error.

[Fix] Fix a bug in pytorch2onnx.py when `num_classes <= 4`

---

tools/train.py

The first line of cfg.text is the config filename, which will not be parsed by this line:
https://github.com/open-mmlab/mmcv/blob/de4f14e9cd547fb8bf886a362ad4f02a0be95141/mmcv/runner/base_runner.py#L346
Use cfg.pretty_text instead.

[Fix] Fix bug: Resume can not work.

---

docs/tutorials/1_config.md

By default after each epoch, evaluation is done for top-5 accuracy. It's possible to set this top-k accuracy but it's missing from the docs. One has to go to the [source code](https://mmaction2.readthedocs.io/en/latest/_modules/mmaction/datasets/base.html?highlight=top_k_accuracy#) in order to find out what to do.
One-liner to document metric_options

add metric_options to docs

---

tools/data/ava/README.md
tools/data/ava/README_zh-CN.md
tools/data/ava/extract_rgb_frames_opencv.sh

Fix #806 
[related comment](https://github.com/open-mmlab/mmaction2/issues/806#issuecomment-819959911)
> For ava, each video must have a fixed number(27030) of frames.
> It seems OpenCV cannot do that [opencv/opencv#9053 (comment)](https://github.com/opencv/opencv/issues/9053#issuecomment-404261402)
> 
> > It seems to me that the problem is that VideoCapture ignores all duplicate frames, while FFmpeg will return duplicates without issues
> 
> I would recommend that AVA dataset should not extract frames by OpenCV and we should remove related docs in tutorials.
> 
> For other dataset, there is no requirement on the number of frames for each video, so extracting frames by OpenCV is ok.
Remove docs and script that extracting ava rgb frames by OpenCV

[Fix] Fix 806

---

mmaction/datasets/base.py

I was training my own multi-label classification dataset using metric ```mmit_mean_average_precision```, and a KeyError occurred:
```
KeyError: 'mean_average_precision'.
```
I found that the evaluation results of metric ```mmit_mean_average_precision```were stored in the dictionary ```eval_results```using a wrong key name ```mean_average_precision```, which is responsible for this error.
Corrected the key name of dictionary ```eval_results```  in the file ```mmaction/datasets/base.py ```.
After this correction, the training process is running normally now.

[fix] Correct the key name of  ‘eval_results’ dictionary for metric 'mmit_mean_average_precision'

---

demo/demo_spatiotemporal_det.py
demo/webcam_demo_spatiotemporal_det.py

Fix #876 
Create a new label map based on custom classes
Modify 2 stdet demos, create a new label map based on stdet config and original label map.

[Fix] Fix#876 

---

demo/README.md
demo/long_video_demo.py

#862 
Currently `long_video_demo.py` only outputs videos. But it will also be beneficial to have it output a JSON file with predictions for each frame.
Modified `long_video_demo.py` by adding a new function to keep track of predictions and write them to a JSON file.
Call `long_video_demo.py ` by providing a `.json` file as `OUT_FILE`

862 add json output video demo

---

configs/recognition/tsn/tsn_r50_320p_1x1x3_110e_kinetics400_flow.py
configs/recognition/tsn/tsn_r50_320p_1x1x8_110e_kinetics400_flow.py
configs/recognition/tsn/tsn_r50_320p_1x1x8_150e_activitynet_clip_flow.py
configs/recognition/tsn/tsn_r50_320p_1x1x8_150e_activitynet_video_flow.py
demo/demo_gradcam.py
mmaction/apis/inference.py
tests/test_runtime/test_inference.py

1. As #904 and the following comment shows, for now, in `inference_recognizer` we assumes files in `video_path` are all named with filename_tmpl. This pr removes the above restriction.
https://github.com/open-mmlab/mmaction2/blob/f007661ab97b206bfb82ed7f815999e2d7964a9b/mmaction/apis/inference.py#L112
2. We have already provided a way to fix bug in #565. However, we haven't modified related configs. So if we train flow models with default config, this shape mismatch bug still occurs.
1. For `inference_recognizer`, this pr count the file that filename format matches `filename_impl`, add some unittests. 
2. For TSN Flow configs, this pr modifies `in_channels` of `backbone`

Support number counting for flow-wise filename template

---

docs/tutorials/1_config.md

It's possible to set the top-k accuracy during the testing phase but it's missing from the docs.
Update the Config tutorial 1 accordingly.

add topk acc for testing to docs

---

demo/README.md
demo/long_video_demo.py

Make font color in `long_video_demo.py` controllable by fetching it as args to the script. Otherwise one has to modify the code.
Small modifications at `long_video_demo.py`
Updated docs accordingly

[Improvement] Add font color to args in long_video_demo

---

demo/long_video_demo.py
tools/analysis/check_videos.py

There are some problems with the `check_videos.py` script. I didn't see any current PR or issues on it so made this one.
Also improved some minor stuff.
- [pool.join()](https://github.com/open-mmlab/mmaction2/blob/master/tools/check_videos.py#L143) was being called before [pool.close()](https://github.com/open-mmlab/mmaction2/blob/master/tools/check_videos.py#L146). It should be the other way around. This also leads to the following error:
```
Traceback (most recent call last):
File "tools/check_videos.py", line 143, in <module>
pool.join()
File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 659, in join
raise ValueError("Pool is still running")
ValueError: Pool is still running
```
- Getting file length
The current way, …

Improve check videos

---

mmaction/apis/train.py

I successfully trained my own model, but the '--test-best' command failed, and I got the warning:
```bash
Warning: test_best set as True, but is not applicable (eval_hook.best_ckpt_path is None)
```
The log is illustrated below:
```bash
2021-07-02 20:50:59,190 - mmaction - INFO - Epoch [1][1380/1407]      lr: 5.000e-05, eta: 0:00:05, time: 0.209, data_time: 0.000, memory: 4292, top1_acc: 0.8551, top5_acc: 0.9902, loss_cls: 0.4914, loss: 0.4914, grad_norm: 6.8683
2021-07-02 20:51:03,350 - mmaction - INFO - Epoch [1][1400/1407]      lr: 5.000e-05, eta: 0:00:01, time: 0.208, data_time: 0.001, memory: 4292, top1_acc: 0.8766, top5_acc: 0.9922, loss_cls: 0.4400, loss: 0.4400, grad_norm: 6.0801
2021-07-02 20:51:05,010 - mmaction - INFO - Saving checkpoint at 1 epochs …
```

[Fix] Fix --test-best failure due to 'eval_hook' wrong assignment

---

.github/workflows/build.yml
tests/test_data/test_pipelines/test_augmentations/test_crop.py
tests/test_data/test_pipelines/test_augmentations/test_lazy.py

Will run CI for torch 1.5.0, 1.7.0, 1.9.0

[Fix] Upgrade CI

---

tools/data/resize_videos.py

Current ``resize_videos.py`` doesn't support resizing **.webm** videos. 
1. It can be solved by change the ``-c:v libx264`` to ``-c:v libvpx``: https://github.com/open-mmlab/mmaction2/blob/cf15d56ca36ef5ad96463503f3935d8bb0b4c726/tools/data/resize_videos.py#L34
2. Or just outputting **.mp4** videos, which is what this PR does. 
I choose the second solution because I found writing **.mp4** files saved lots of time. BTW, it requires lots of **extra** time to write the resized videos (which run in the background) **after** the python script execution is finished.
Add ``--to-mp4`` argument, to output .mp4 files.
I had tested it on the ActivityNet dataset, which contains .mkv, .webm abd .mp4 videos.

add --to-mp4 argument to resize_videos.py

---

mmaction/datasets/pipelines/loading.py
tests/test_data/test_pipelines/test_loadings/test_sampling.py

This PR enables `class SampleFrames` with ability to sample tail frames.
Test Codes
```python
from mmaction.datasets.pipelines import SampleFrames
from matplotlib import pyplot as plt
import numpy as np
f = dict(total_frames=1000, start_index=0)
s = SampleFrames(clip_len=1, num_clips=128, keep_tail_frames=True)
a = []
for i in range(1000):
a.append(s(f)['frame_inds'])
a = np.stack(a)
u, counts = np.unique(a, return_counts=True)
b = []
for i in range(1000):
try:
b.append(counts[u.tolist().index(i)])
except ValueError:
b.append(0)
plt.plot(b)
plt.show()
```
Results

[Improvement] add option to keep tail frames

---

demo/demo.py
demo/demo_gradcam.py
demo/demo_posec3d.py
docs/getting_started.md
docs/install.md
docs_zh_CN/getting_started.md
docs_zh_CN/install.md
mmaction/apis/inference.py
tests/test_runtime/test_inference.py

Motivation:
1. More flexible inference: The dataset type of the config and actual data format does not need to match
2. More modalities: Support skeleton-based
3. Flexible API: Can take path str, dictionary, or numpy array (to support torch serve) as inputs. 
@dreamerlin, @gengenkai  Please leave some comments if you have more ideas.

[Improvement] Refactor Inference API

---

mmaction/apis/train.py
mmaction/datasets/builder.py
mmaction/datasets/pipelines/__init__.py
tools/analysis/bench_processing.py
tools/analysis/benchmark.py

If the default value of persistent_workers is True and cannot be configured in the config file.  You can not train with num_workers=0.

[Fix] switch the default value of persistent_workers to False

---

mmaction/datasets/ava_dataset.py
mmaction/datasets/pipelines/loading.py
tests/test_data/test_datasets/test_ava_dataset.py

according to https://github.com/open-mmlab/mmaction2/blob/2ff37975b9ea5851a071909c9847b89132c5f99d/docs/faq.md#data
start_index is used to set the offset. However, start_index is not used in SampleAVAFrames
https://github.com/open-mmlab/mmaction2/blob/28ac80cb1a/mmaction/datasets/pipelines/loading.py#L1278
#1277

Fix bug that start_index is not used in RawFrameDecode

---

mmaction/core/evaluation/ava_utils.py
mmaction/models/heads/fbo_head.py
mmaction/models/heads/lfb_infer_head.py

As per Issue #1382, Spatio-Temporal Localisation using the LFB model was failing.
In addition, there was a slight bug in the printing of the assertion error when the exclusion file had too many (or too little) columns.
1. Added a `pretrained` argument (default None, and unused) to the `__init__()` of LFBInferHead
2. Refactored the way the length of a row is displayed in `ava_utils.read_exclusions()`

Fixed Issue #1382 and a Printout Bug

---

mmaction/models/heads/base.py

Support topk customizing in models/heads/base.py

[Feature] Support topk customizing in models/heads/base.py

---

tools/data/kinetics/rename_classnames.sh

```bash
mmaction2/tools/data/kinetics$ bash rename_classnames.sh kinetics400
We are processing kinetics400
rename_classnames.sh: line 29: cd: ../../tools/data/kinetics400/: No such file or directory
```
```shell
cd ../../tools/data/kinetics/
```

fix cd wrong dir error

---

docs/getting_started.md

The test examples in [High-level APIs for testing a video and rawframes](https://mmaction2.readthedocs.io/en/latest/getting_started.html#high-level-apis-for-testing-a-video-and-rawframes) don't work, which is caused by the wrong argument `labels` passed to `inference_recognizer`. The declaration of `inference_recognizer` is `def inference_recognizer(model, video, outputs=None, as_tensor=True, **kwargs)`, and the argument  `outputs` is names of layers whose outputs need to be returned not the filepath of the labels.
I remove the argument `labels` passed to `inference_recognizer` and since the argument `use_frames` in `init_recognizer` is deprecated PR #1191, I remove it too.

[Update] High-level APIs for testing a video and rawframes not working

---

mmaction/apis/train.py

To be short, if the priority of EvalHook is higher than IterTimerHook, it will cause KeyError: 'data_time'
This PR is based on (https://github.com/open-mmlab/mmdetection/pull/5882, https://github.com/open-mmlab/mmsegmentation/pull/766), where details can be found.
Set the priority of `EvalHook` to `LOW`

[Fix] Fix the log error when `IterBasedRunner` is used 

---

mmaction/apis/train.py
mmaction/core/dist_utils.py
mmaction/utils/__init__.py
mmaction/utils/distribution_env.py
tools/test.py

Support Cambricon MLU device for MMaction2.
Support Cambricon MLU device for MMaction2.
mmaction/apis/train.py : train on the default device.
tools/test.py : test on the default device.
mmaction/utils/distribution_env.py : choose the default device; build ddp and dp model.
No BC-breaking
you can use the native script  of gpu devices to train the model on mlu devices without any change.

feat(mlu): Support MLU Backend

---

docs/tutorials/1_config.md
docs_zh_CN/tutorials/1_config.md

The origin url in config tutorial is 404 now. I think mmcv has updated the new url, so i replace them in both en and zh_CN files.
in both en and zh_CN config tutorial files

fix url in config tutorial when talking about Config File Structure

---

docs/data_preparation.md
docs_zh_CN/data_preparation.md
tools/data/build_audio_features.py
tools/data/extract_audio.py

all fixes happen in file `tools/data/extract_audio.py` and `tools/data/build_audio_features.py`
1. use the same `args.ext` style, that is like `mp4` or `wav` without a `.`. This is the same style in videos.
2. for `num-workers`, both use `args.num-workers`, for in original `extract_audio.py` it's `args.num-worker` 
3. change the args of glob() in `build_audio_features.py`, for the origin matching scheme is wrong. You can see #1628 . I change the matching scheme the same with `extract_audio.py` and that is the same with other videos files.
4. There is another issue that i did not mention in Issue 1628, that is in `extract_audio.py` line 21, we should use `{line}` not `./{line}` to get the right video path for extracting audio.
5. Fix expressions in tutorial.md both in en and zh_CN for …

Fix issues in audio module

---

tools/data/extract_audio.py

Fix a typoe in the "extract_audio.py" file.
In the "extract_audio.py" file, the argument `--num-worker` was changed to `--num-workers` but `args.num_worker` wasn't changed accordingly. In this PR, `args.num_worker` is changed to `args.num_workers` to avoid errors.
No

Fix a typo in "extract_audio.py": args.num_worker -> args.num_workers

---

mmaction/models/backbones/resnet_tsm.py

The initialization of TSM model will change the network parameters. In the new version of mmengine, test-only mode will not call the initialization function and thus cannot load trained checkpoints.
Move the codes in the function `init_weights` from the class `ResNetTSM` to the `__init__` function.

[Fix] fix BC breaking for TSM initialization

---

configs/detection/ava/slowfast_kinetics_pretrained_r50_8x8x1_20e_ava_rgb.py

The url of the pertaining checkpoint in the AVA detection model is invalid. Just fix the url.

[Fix] the wrong url for pertaining models

---

mmaction/models/__init__.py
mmaction/models/task_modules/assigners/max_iou_assigner_ava.py

Fix some invalid module imports due to mmdet APIs changed.

[Fix] invalid import due to mmdet APIs changed

---

mmaction/datasets/__init__.py
mmaction/datasets/ava_dataset.py
mmaction/datasets/base.py
mmaction/datasets/pose_dataset.py
mmaction/datasets/rawframe_dataset.py
mmaction/datasets/video_dataset.py
mmaction/models/heads/base.py

- Since there are some common attributes and class funcions shared between different ``dataset`` classes, it's better to abstract a base dataset to simplify some apis.
- ``label_smoothing`` should not only be supported in multi-class cases as sugested in https://github.com/open-mmlab/mmaction2/issues/1639

[Refactor] Add ``BaseActionDataset`` and ``label_smoothing``

---

mmaction/models/recognizers/base.py

This PR is similar to https://github.com/open-mmlab/mmcv/pull/2246, but doesn't depend on it. We focus on using the new methods introduced by TorchVision's [Model Registration API](https://pytorch.org/blog/easily-list-and-initialize-models-with-new-apis-in-torchvision/).
It adopts the new `torchvision.models.get_model()` method to initialize a model by its name instead of using directly `torchvision.models.__dict__`.
Looking forward to your feedback (see https://github.com/pytorch/vision/issues/6365).

Add support of TorchVision's Model Registration API on MMAction2

---

requirements/optional.txt

[Fix] fix colab bug
this pr fix bug in [issue](https://github.com/open-mmlab/mmaction2/issues/1943)
default moviepy version in colab environment is too low, and not compatible with imageio now.

[Fix] fix colab bug

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

add coverage test on cuda device

[CI] add coverage test on cuda device

---

.pre-commit-config.yaml

The motivation to upgrade some versions of pre-commit hooks to latest is that importlib-metadata v5.0.0 which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581.
Upgrade some versions of pre-commit hooks.
If so, please describe how it breaks the compatibility and how users should modify their codes to keep …

Upgrade pre commit hooks in dev-1.x

---

.circleci/test.yml
.github/workflows/build.yml
requirements/optional.txt
setup.cfg
tests/test_models/test_recognizers/test_recognizer2d.py

latest version timm rely on pytorch>=1.7, fix related bugs in CI

[CI] fix timm related bug for master

---

mmaction/datasets/transforms/wrappers.py

[fix] fix imgaug wrapper for dev1.x

[fix] fix imgaug wrapper for dev1.x

---

configs/_base_/default_runtime.py
docs/en/user_guides/4_train_test.md
tools/train.py

Before this update:
```python
python tools/train.py configs/recognition/swin/swin-tiny-p244-w877_in1k-pre_8xb8-amp-32x2x1-30e_kinetics400-rgb.py \
--cfg-options randomness.seed=0 randomness.deterministic=True
```
After this update:
```python
python tools/train.py configs/recognition/swin/swin-tiny-p244-w877_in1k-pre_8xb8-amp-32x2x1-30e_kinetics400-rgb.py \
--seed 0 --deterministic
```

[Improvement] Add `SyncBuffersHook` and `Seed`

---

tools/deployment/mmaction2torchserve.py

Fix deploy script for v1.0
switch mmcv to mmengine where appropriate

[Fix] switch mmaction2totorchserve from mmcv to mmengine

---

.github/workflows/lint.yml

[fix] fix lint ci config

---

demo/README.md
demo/webcam_demo.py

支持real-time webcam demo
New webcam demos in the new 1.x version of mmaction2
Add a new file —>webcam_demo.py
python webcam_demo.py \
../tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb.py \
../tsn_imagenet-pretrained-r50_8xb32-1x1x8-100e_kinetics400-rgb_20220906-2692d16c.pth \
../tools/data/kinetics/label_map_k400.txt \
--device=cpu

CodeCamp #153

---

mmaction/datasets/__init__.py
mmaction/datasets/repeat_aug_dataset.py
requirements/build.txt
tests/datasets/test_repeataug_dataset.py

[Feature] support repeat_aug

---

.pre-commit-config.yaml

[Fix] upgrade isort to fix ci

---

tools/data/sthv2/README.md
tools/data/sthv2/README_zh-CN.md

The paths of sthv2 dataset's annotation file is hardcoded.
https://github.com/open-mmlab/mmaction2/blob/dbb8f064151a90be647846bcfafb43fd2b523c3f/tools/data/parse_file_list.py#L243-L247
which will fail when user follows the sthv2 dataset preparation document to generate the file list
added renaming script to **Step 1. Prepare Annotations** in both `tools/data/sthv2/README.md` and `tools/data/sthv2/README_zh-CN.md`

Fix sthv2 dataset annotations preparation document

---

mmaction/datasets/transforms/loading.py

[fix] rename fps in DecordInit to avoid overwriting fps in SampleAVAFrames

[fix] rename fps in DecordInit to avoid overwriting fps in SampleAVAFrames

---

mmaction/models/backbones/resnet.py
mmaction/models/backbones/resnet3d.py
mmaction/models/backbones/resnet3d_slowfast.py
mmaction/models/backbones/timesformer.py

[fix] specify map_location to cpu when use _load_checkpoint to avoid load ckpt to cuda:0 for all cuda devices.

[fix] specify map_location to cpu when using _load_checkpoint

---

configs/localization/bmn/README.md
configs/localization/bsn/README.md
configs/localization/bsn/bsn_tem_1xb16-400x100-20e_activitynet-feature.py

[Fix] fix command bugs in localization tasks' README

---

docs/en/useful_tools.md
docs/zh_cn/useful_tools.md

The document in `useful_tools.md` contains an error, the folder param `analysis` is missing in the command execution section.
https://github.com/open-mmlab/mmaction2/blob/master/tools/analysis/print_config.py
Change the doucument.
3. If the modification has potential influence on downstream projects, this PR should be …

[Doc] fix outdated links in the documentation

---

demo/demo_configs/faster-rcnn_r50-caffe_fpn_ms-1x_coco-person.py
mmaction/apis/inference.py
mmaction/utils/misc.py
tools/data/skeleton/README.md
tools/data/skeleton/README_zh-CN.md
tools/data/skeleton/ntu_pose_extraction.py

[fix] fix ntu_pose_extraction

---

README.md
README_zh-CN.md
demo/demo_configs/faster-rcnn_r50_fpn_2x_coco_infer.py
docs/en/get_started/installation.md

[Doc] Update Installation Related Doc

---

docs/en/advanced_guides/customize_dataset.md
docs/en/advanced_guides/customize_logging.md
docs/en/advanced_guides/customize_pipeline.md
docs/en/get_started/overview.md
docs/en/get_started/quick_run.md
docs/en/merge_docs.sh

- Refine docs/en/advanced_guides/customize_dataset.md
- Refine docs/en/advanced_guides/customize_logging.md
- Refine docs/en/advanced_guides/customize_pipeline.md
- Refine docs/en/get_started/overview.md
- Refine docs/en/get_started/quick_run.md

[Doc] Refine Docs

---

mmaction/evaluation/metrics/acc_metric.py
mmaction/models/heads/base.py
mmaction/models/losses/cross_entropy_loss.py
tests/evaluation/metrics/test_acc_metric.py

https://github.com/open-mmlab/mmaction2/issues/2416
fix a bug in multi-label classification.
Check whether is single-label before adding to the `self.results`.
```python
if label['item'].size(0) == 1:
result['label'] = label['item'].item()
else:
result['label'] = label['item'].cpu().numpy()
```

[Fix] fix a bug in multi-label classification

---

.github/workflows/pr_stage_test.yml
mmaction/models/utils/blending_utils.py
tools/train.py

Fix a warning caused by `torch.div`. See issue https://github.com/open-mmlab/mmaction2/issues/2446.

[Fix] Fix a warning caused by `torch.div`

---

.readthedocs.yml

[Fix] Fix error raised by incompatible OpenSSL version

[Fix] Fix readthedoc error raised by incompatible OpenSSL version

---

mmaction/testing/__init__.py
tests/models/recognizers/test_recognizer2d.py

[UT] add ut for recognizer 2d

---

docs/en/get_started/faq.md

[Doc] update faq

---

mmaction/models/backbones/mvit.py
mmaction/models/heads/mvit_head.py

Resolve the problem when class token is taken away in MViT. 
Put more precisely, when `with_cls_token` and `output_cls_token` are both set `False` in model `MViT`, an error would occur because its `MultiScaleBlock`and `MultiScaleAttention` components don't pass the `with_cls_token` argument from class `MViT`, and set it `True` by default.

[Fix] Fix a bug of MViT when set with_cls_token to False 

---

tools/data/gym/download.py
tools/data/gym/download_videos.sh
tools/data/gym/trim_event.py
tools/data/gym/trim_subaction.py

The MMCV package now has version 2.0.0, which removes the function `mmcv.load()`, causing the following error when running tools/data/gym/download_videos.sh:
Traceback (most recent call last):                                                                                                                                                                                     
File "download.py", line 100, in <module>                                                                                                                                                                            
main(**vars(p.parse_args())) …

[Fix] Update outdated dependencies of mmcv for downloading fine-gym dataset

---

.circleci/test.yml
configs/recognition/tsn/custom_backbones/tsn_imagenet-pretrained-swin-transformer_8xb32-1x1x3-100e_kinetics400-rgb.py
mmaction/models/recognizers/base.py
mmaction/models/recognizers/recognizer2d.py
tests/models/recognizers/test_recognizer2d.py

[Fix] Fix BC-breaking of timm for TSN

[Fix] Fix BC-breaking of timm for TSN

---

tools/analysis_tools/confusion_matrix.py

[Fix] Close `FileHandler` in Windows to make the temporary directory can be deleted

[Fix] Close `FileHandler` in Windows to make the temporary directory can be deleted

---

demo/demo_skeleton.py

In skeleton-based action recognition demo, arrays are created with dimension num_person, but when fewer people are detected in some frames, the keypoints data is jagged and there's a dimension mismatch error. #2572
If there isn't enough keypoints data, only fill the first slots of the array.

[Fix] Fix mismatch when number of people changes

---

demo/README.md
demo/demo_audio.py
mmaction/apis/inference.py

[Feature] Add audio demo

---

tools/test.py
tools/train.py

[Enhancement] Support flexible runner

[Enhancement] Support flexible runner
